[package]
name = "learning_rocket"
version = "0.1.0"
authors = ["tonimctoni <>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde_derive = "*"
serde = "*"
serde_json = "*"